name: py3.7
channels:
  - pytorch
  - defaults
dependencies:
  - babel=2.9.1=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2022.3.29=haa95532_0
  - certifi=2021.10.8=py37haa95532_2
  - cffi=1.15.0=py37h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37haa95532_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py37h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - freetype=2.10.4=hd328e21_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.11.3=py37haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.2=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - nltk=3.7=pyhd3eb1b0_0
  - numpy=1.21.5=py37ha4e8547_0
  - numpy-base=1.21.5=py37hc2deb75_0
  - openssl=1.1.1n=h2bbff1b_0
  - pillow=9.0.1=py37hdc2b20a_0
  - pip=21.2.4=py37haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=h6244533_0
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - regex=2022.3.15=py37h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - setuptools=58.0.4=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=h2bbff1b_0
  - tk=8.6.11=h2bbff1b_0
  - torchaudio=0.11.0=py37_cu113
  - torchvision=0.12.0=py37_cu113
  - tqdm=4.63.0=pyhd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=hbd8134f_5
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - docopt==0.6.2
    - greenlet==1.1.2
    - records==0.5.2
    - sqlalchemy==1.1.14
    - tablib==3.2.1
    - zipp==3.8.0
